### ISSUE TITLE
Contact Us Section

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#12]
@zkysar Does this template have a contact us section? Could you add it to the end if there is? Don't worry about php email function, we can do it through a simple http form submission without a backend.

**Comment by zkysar** [comment]
They've got a modal that I took out will this work?
https://puu.sh/uVeVW/e3c87982f7.png

**Comment by sunyu912** [comment]
Yes, could we try to embed this into the page? If not, a dialog is also
fine.

Just put the form there and I will take care of sending it.
