### ISSUE TITLE
Align the Images

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#13]
<img width="1248" alt="screen shot 2017-03-21 at 6 57 30 am" src="https://cloud.githubusercontent.com/assets/1639351/24150690/b1c3bc9c-0e03-11e7-8711-d4c68fa70f79.png">

**Comment by sunyu912** [comment]
@Cnibungco Could we reduce the size of some of those images so that we can align the text "CS Department" "College of Science" "CPP" in the same line?

**Comment by Cnibungco** [comment]
done
