### ISSUE TITLE
Add similar bullets to criteria

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#16]
We can do something similar as the Computer Lab Rules

<img width="1216" alt="screen shot 2017-03-22 at 2 21 07 pm" src="https://cloud.githubusercontent.com/assets/1639351/24221310/16fe902a-0f0b-11e7-8d9d-df4c93e673a2.png">

**Comment by Cnibungco** [comment]
done
