### ISSUE TITLE
Closest parking lot link goes nowhere

### ISSUE THREAD

**Issue by Cnibungco** [cpp-coding-challenge/cpp-coding-challenge.github.io#18]
Is it supposed to redirect to google maps pin/location?

**Comment by sunyu912** [comment]
Let's make a Google Map pin link to Parking Lot J

**Comment by cassilam** [comment]
Link redirects to Google Maps with pin on Parking Lot J

**Comment by sunyu912** [comment]
Hi Cassi,

Could you change the <a> to target="blank" so that it will be opened in the new tab? See below:

https://www.thesitewizard.com/html-tutorial/open-links-in-new-window-or-tab.shtml

**Comment by cassilam** [comment]
The link now opens in a new tab
