### ISSUE TITLE
Add Sponsors Icons

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#23]
"This year’s awards are provided by our sponsors:" 

Let's put the Company Icon there. For now, we only have Northrop Grumman. Let's just put an icon there.

**Comment by cassilam** [comment]
Added the icon to img folder and webpage

**Comment by sunyu912** [comment]
This might be a little picky, but could we find an icon with a transparent background (rather than white)?

**Comment by cassilam** [comment]
How about now?

**Comment by sunyu912** [comment]
Looks awesome!
