### ISSUE TITLE
Replace "Example Problems" with "Previous Contests"

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#24]
"The contest problems are available from the following past competitions:"

HSPC 2017   [Link to the problem PDF]  [Link to the photos] 

The PDF can be found here:

[SoCal_HSPC_2017_without_answers.pdf](https://github.com/cpp-coding-challenge/cpp-coding-challenge.github.io/files/1553892/SoCal_HSPC_2017_without_answers.pdf)

I will provide the photos link separately. 

Also, let's show the results from the last year in a table, with the different categories and the top 5. The result can be found at here:

[HSPC-AwardCeremony.pdf](https://github.com/cpp-coding-challenge/cpp-coding-challenge.github.io/files/1553898/HSPC-AwardCeremony.pdf)

**Comment by sunyu912** [comment]
The photo link is: https://www.dropbox.com/sh/5f2y44k7arlt9fp/AABpXn_rT7eKGTHCGiD9B4sUa?dl=0

**Comment by cassilam** [comment]
Added a table displaying 2017 results and linked the photo album and problems

**Comment by sunyu912** [comment]
Looks great. A few minor things to update:

1) Let's add the date May 20th, 2017 to this event "HSPC 2017" 
2) I think the Photo Slider looks really good, so let's just hide "View All Photos"
3) Let's highlight "View Problems" with the bold or something else
4) For "Best Team Collaboration", let's add a 6th place, so that you can place all 6 teams there.

Thanks Cassi!

**Comment by cassilam** [comment]
Changes have been made as requested.

**Comment by sunyu912** [comment]
Looks great!
