### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#26]
1. Add a Question in Frequently Asked Questions (FAQ)

Where can I find some sample questions?

You can view the contest questions in the previous contest at here.

* here should be a internal page link to the Previous Contests section.

2. Delete the following bullet:

For each incorrect submission, a penalty of 20 minutes will be assessed to the contestant.

**Comment by cassilam** [comment]
FAQ Updated

**Comment by sunyu912** [comment]
The layout looks not right. Can you see the same?

<img width="1186" alt="screen shot 2017-12-12 at 10 50 11 pm" src="https://user-images.githubusercontent.com/1639351/33925480-dfcb1ac4-df8e-11e7-8722-e6378e4646fc.png">

**Comment by cassilam** [comment]
I just changed the position of the question. How is it now?

**Comment by sunyu912** [comment]
Looks awesome!! Great job Cassi!
