### ISSUE TITLE
Update the Menu Option for "Example"

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#28]
<img width="795" alt="screen shot 2017-12-12 at 10 38 49 pm" src="https://user-images.githubusercontent.com/1639351/33925060-7ee3ea34-df8d-11e7-8a57-0ef65b848b79.png">

**Comment by cassilam** [comment]
Changed the link from 'Examples' to 'Previous Contests'
