### ISSUE TITLE
Temporarily Hide "Directions" Button

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#30]
<img width="1162" alt="screen shot 2017-12-12 at 10 59 28 pm" src="https://user-images.githubusercontent.com/1639351/33925753-2f9210ca-df90-11e7-9fbb-527226532b1b.png">

Also, add the text:

"May 19, 2018 10:30am - 4:00pm" -> "May 19, 2018 10:30am - 4:00pm @ Cal Poly Pomona"

**Comment by cassilam** [comment]
Commented out the "Directions" button and added "@ Cal Poly Pomona"
