### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#31]
Hi Cassi,

Thanks again for the quick update on the website. That's very impressive!

I am wondering if you have done graphics editing before. For instance, are you able to edit the logo we current have and get rid of the SoCal from it:

![image](https://user-images.githubusercontent.com/1639351/33926025-6da64862-df91-11e7-8679-4ffd7c6e10e6.png)

No worries if you don't know or don't have the tool to do it. I can also contact some graphics designer to handle it.

Yu

**Comment by sunyu912** [comment]
Also, if you have other ideas on the Logo, that would be great too. Just something for HSPC.

**Comment by cassilam** [comment]
Hi Dr. Sun,

I heard Anthony mention that he’s had experience with things like that. Maybe you can ask him?

Sincerely,
Cassi Lam

**Comment by sunyu912** [comment]
Yes, no worries Cassi. I will have some of our designers to take care of it. 

Take some sleep! Thanks again for the quick help.

**Comment by cassilam** [comment]
I removed “SoCal” from the logo.

**Comment by sunyu912** [comment]
Looks great!! Thanks Cassi.
