### ISSUE TITLE
Correct the Rank in Grace Hopper Award

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#32]
No 3 vs No 4?

<img width="780" alt="screen shot 2017-12-27 at 10 53 14 am" src="https://user-images.githubusercontent.com/1639351/34390368-412dc760-eaf4-11e7-87c5-4841397ced5c.png">

**Comment by sunyu912** [comment]
Please see my slides for the result.

**Comment by cassilam** [comment]
I made a typo regarding her score. It has already been fixed.
