### ISSUE TITLE
Add a New Sponsor

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#33]
Let's find out a nice logo or icon for it and add it to our sponsors section.

https://kronosaur.com/

**Comment by cassilam** [comment]
I found a logo for it but I don't think I can make the background transparent.

**Comment by sunyu912** [comment]
Let me ask.

**Comment by sunyu912** [comment]
Here is the logo:

https://ministry.kronosaur.com/res/KronosaurLogo.jpg

Also, let's make the logo clickable and link it to the company website.

**Comment by cassilam** [comment]
Added the logo and linked the logos to the companies' websites

**Comment by sunyu912** [comment]
Great. Could we also add the game there?


http://kronosaur.com/res/TranscendenceTile.jpg

https://transcendence.kronosaur.com/

**Comment by cassilam** [comment]
Transcendence has been added too

**Comment by sunyu912** [comment]
Thanks Cassi. Could we align them in the same row with some margins? Also,
let's make the game logo the same height as the other one.

**Comment by cassilam** [comment]
Which CSS file are the styling for the sponsor icons located

**Comment by sunyu912** [comment]
I don't think we had the style specific for these icons. Feel free to make
a new one.

**Comment by cassilam** [comment]
I resized the logos to have the same height and aligned the Kronosaur Productions icons to be on the same row

**Comment by sunyu912** [comment]
Perfect!
