### ISSUE TITLE
Revise the Competition to Cover Middle School

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#34]
With lots of feedback, I think we can expand it to the middle school level. We need to figure out the things to be changed:

- We need to edit the eligibility to include 6-8 grade levels. 

- For awards, I am thinking to have the same set of awards, but probably not top 5 winners (I don't know how many we can get), maybe just 3 or not listed. We need to clarify that the awards will be for different grade levels (middle/high schools).

- The challenge part is the naming. What to change for "HSPC"? I don't have to change it, if we can figure out a way to specify it. For instance, we can just add an announcement for "Pre-High School" category, or something like that.

Could we modify the content and info for this change?

**Comment by sunyu912** [comment]
Is this supposed to be here?

<img width="1417" alt="screen shot 2018-02-22 at 8 22 49 pm" src="https://user-images.githubusercontent.com/1639351/36577958-610377ae-180f-11e8-84d0-209535ff55a5.png">

**Comment by cassilam** [comment]
I centered the sentence
