### ISSUE TITLE
Add a Section to Allow Users to Sign Up a Email List

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#40]
Let's use https://mailchimp.com/help/add-a-signup-form-to-your-website/

**Comment by sunyu912** [comment]
@FosterSamuel Could you help to look into this one and build a Mailchimp integration into the website?

**Comment by FosterSamuel** [comment]
@sunyu912 Mailing list is now in. Just to check: we are still using the Wufoo form for actual signups though, correct?

**Comment by sunyu912** [comment]
Yes
