### ISSUE TITLE
Urgent - Create a Flyer for the Event

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#42]
I would recommend using a nice and professional template to make something quickly. 

I use this site a lot recently:

https://www.canva.com/templates/flyers/

**Comment by FosterSamuel** [comment]
I have no experience with designing flyers. Made this draft. Thoughts? @sunyu912 

[CPP HSPC Flyer.pdf](https://github.com/cpp-coding-challenge/cpp-coding-challenge.github.io/files/2896117/CPP.HSPC.Flyer.pdf)

<img src="https://user-images.githubusercontent.com/15165138/53275752-1fac2f00-36b1-11e9-9be7-0360c4584032.JPG" width="50%">

**Comment by sunyu912** [comment]
Thanks Sam. A few notes:

- URL: https://www.cpp.edu/~hspc/
- Put the time range also 
- Mention pre-high school categories (6-8) is also available
- Put our sponsors if it's easy to do with this template, if not, don't worry about it

**Comment by FosterSamuel** [comment]
@sunyu912 

[CPP HSPC Flyer.pdf](https://github.com/cpp-coding-challenge/cpp-coding-challenge.github.io/files/2897177/CPP.HSPC.Flyer.pdf)
<img src="https://user-images.githubusercontent.com/15165138/53290738-3740f180-375d-11e9-8452-884935e97466.png" width="50%">

**Comment by sunyu912** [comment]
Looks great! Thanks Sam!
