### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#43]
This year, let's have one member to consistently try contacting and getting sponsors. 

This is not easy, but if we try hard, that should be something available.

**Comment by sunyu912** [comment]
@FosterSamuel @JTokos This is a relatively challenging task, since most of companies do not handle it. From our past experiences, some of the useful tips are:

- Use your student hat
- Contact our alumni or your connections
- Find out the most related companies

**Comment by sunyu912** [comment]
One more thing important, we need to make contacts and try it every week consistently.

**Comment by FosterSamuel** [comment]
Working on this with @JTokos -- he compiled a list of 300+ companies. Narrowing it down to companies that match values. We'll be sending out sponsorship request emails from here on out.

**Comment by sunyu912** [comment]
Thanks Sam. This is so helpful! Let's start sending them soon as this is
getting closer.
