### ISSUE TITLE
Form the Core Event Management Team

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#44]
3-4 members is preferred

**Comment by FosterSamuel** [comment]
Core Team:
- Justin Tok (Sponsorship)
- Kiana Ziglari (MailChimp, Volunteer Recruiting)
- Samuel Foster (Lead)

@sunyu912 Can you please invite  https://github.com/JTokos and https://github.com/kianazig to this repository so they can begin helping with HSPC?

**Comment by sunyu912** [comment]
Thanks Sam. I just sent out the invite. Welcome aboard Justin and Kiana.
