### ISSUE TITLE
Make the 2019 Announcement using Mailchimp Email Lists

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#45]

**Comment by sunyu912** [comment]
@FosterSamuel Are you able to join the Mailchimp account I sent?

**Comment by sunyu912** [comment]
@kianazig What's your email?

**Comment by kianazig** [comment]
Hi Dr. Sun,

My email is kziglari@cpp.edu.

**Comment by sunyu912** [comment]
Great! Thanks Kiana! I have just invited you. 

I sent a few email contacts a couple of days ago to Sam. Could you please work with him to add them into the HSPC list?

After that, let's prepare and make an announcement to all the lists about HSPC.

**Comment by FosterSamuel** [comment]
@sunyu912 Please review the test email of the draft announcement written by @kianazig. I sent it to your Gmail.

I forwarded the interested emails to Kiana.

**Comment by sunyu912** [comment]
This is great. Please go ahead to send it to all the email lists in the
mailchimp account.

**Comment by kianazig** [comment]
I added the contact info for all the emails into the HSPC interest list and sent out the announcement email to all the lists.

**Comment by sunyu912** [comment]
Thanks so much Kiana.
