### ISSUE TITLE
Add New Sponsors

### ISSUE THREAD

**Issue by sunyu912** [cpp-coding-challenge/cpp-coding-challenge.github.io#48]
Please put the following logos:
- NSF
- NSA
- GenCyber

**Comment by sunyu912** [comment]
Sorry, could we still keep the those sponsors and add all of them together? Also, the logos are too big, could we align them nicely?

**Comment by sunyu912** [comment]
*old sponsors*

**Comment by FosterSamuel** [comment]
Done.
