### ISSUE TITLE
Write Challenge Questions

### ISSUE THREAD

**Issue by FosterSamuel** [cpp-coding-challenge/cpp-coding-challenge.github.io#53]
Working on challenge questions for 2019 HSPC. I will not be sharing any details of the questions here, just tracking progress.

- [x] Question 1
- [x] Question 2
- [x] Question 3
- [x] Question 4
- [x] Question 5
- [x] Question 6
- [x] Question 7
- [x] Question 8

**Comment by sunyu912** [comment]
8 Questions: 2 Easy 3 Medium and 2 Hard. Please see the sample questions in the past year.

**Comment by sunyu912** [comment]
Let's build a slightly different question set for Middle School division.

**Comment by FosterSamuel** [comment]
Challenge questions complete. First is 2 easy, 3 medium, 2 hard. Middle school is 2 easy, 4 medium, 1 hard. 

Please see the two tests. @sunyu912
