### ISSUE TITLE
Social Media Icons at bottom go nowhere

### ISSUE THREAD

**Issue by Cnibungco** [cpp-coding-challenge/cpp-coding-challenge.github.io#8]
Is there a Facebook page or event for this? If not, we could remove the icons or link it to the CPP pages?

**Comment by sunyu912** [comment]
We don't have those. I am wondering if we can change them into "Share" links.

**Comment by Cnibungco** [comment]
Replaced the Social Media icons with FB Share and Twitter Tweet Buttons
